### ISSUE TITLE
代码风格检查 & 持续集成

### ISSUE THREAD

**Issue by jukanntenn** [DjangoStudyTeam/django-China-api#21]
## 导入排序

使用 [isort](https://github.com/PyCQA/isort) 工具对 import 导入进行排序。

isort 支持读取 pyproject.toml 文件中的配置，建议的配置：

```
[tool.isort]
profile = "black"
skip = ["migrations"]
```

将 isort 配置为 PyCharm 的 external 工具，以便在代码开发时随时格式化导入排序，参考文档：[isort Plugins](https://github.com/PyCQA/isort/wiki/isort-Plugins)，建议的 parameters：`--profile black $FilePath$`

## 代码格式化

使用 [black](https://github.com/psf/black) 对代码进行格式化。

black 支持读取 pyproject.toml 文件中的配置，建议的配置：

```
[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | migrations
  )/
)
'''
```

将 black 配置为 PyCharm 的 external 工具，以便在代码开发时随时格式化代码，配置方式同 isort。

## Lint

使用 [flake8](https://flake8.pycqa.org/en/latest/index.html) 和 flake8-isort 进行 LInt 检查，以发现一些代码质量方面的缺陷。

flake8 的配置放在 setup.cfg 文件中，建议的配置：

```
[flake8]
max-line-length = 120
extend-ignore = E203
exclude =
    .tox,
    .git,
    */migrations/*
```

## 持续集成

配置 GitHub Action，在代码被 PR 或者合并到 main 分支时执行这些 CI 操作：

- Lint with flake8
- Lint with black
- Test with pytest

以下是一个 GitHub Action 的参考配置文件：

```yml
name: CI

on: [ push ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v4

      - name: Cache Poetry virtualenv
        uses: actions/cache@v2
        id: poetry-cache
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Dependencies
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: poetry install

      - name: Lint with flake8
        run: poetry run flake8

      - name: Lint with black
        run: poetry run black . --check

      - name: Test with pytest
        run: poetry run pytest
```
